apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-go-app
  template:
    metadata:
      labels:
        app: simple-go-app
    spec:
      containers:
      - name: simple-go-app
        image: gcr.io/cluster-01-290863/test/simple-go-app:signed
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simple-go-app
spec:
  selector:
    app: simple-go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
