apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  params:
    - name: repo_url
    - name: revision
  workspaces:
    - name: source
    - name: basic-auth
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source
        - name: basic-auth
          workspace: basic-auth
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)

    - name: golang-test
      runAfter:
        - fetch-repository
      taskRef:
        name: golang-test
      workspaces:
        - name: source
          workspace: source
      params:
        - name: package
          value: github.com/k8strainer/pipelines-as-code

    - name: noop-task
      displayName: "Task with no effect"
      runAfter:
        - golang-test
      workspaces:
        - name: source
          workspace: source
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: noop-task
            image: registry.access.redhat.com/ubi9/ubi-micro
            workingDir: $(workspaces.source.path)
            script: |
              echo "testrun 01 für Branch v1.0"
              exit 0
